AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: sam app
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x
Resources:
  TempConversionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: temperature.handler
      Layers:
        - !Ref TempConversionDepLayer
      Events:
        Temperature:
          Type: Api
          Properties:
            Path: /{conversion}/{value}
            Method: get
  OfficeCoversionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: office.handler
      Layers:
        - arn:aws:lambda:us-west-2:764866452798:layer:libreoffice:1
      Events:
        Convert:
          Type: Api
          Properties:
            Path: /office
            Method: get
  TempConversionDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-app-dependencies
      Description: Dependencies for sam app [temp-units-conv]
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs10.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain
